TRUNCATE TABLE voting_policies RESTART IDENTITY;
TRUNCATE TABLE voter_policies RESTART IDENTITY;
TRUNCATE TABLE candidate_policies RESTART IDENTITY;
TRUNCATE TABLE session_states RESTART IDENTITY;
TRUNCATE TABLE users RESTART IDENTITY;
